### ISSUE TITLE
error while importing rwt in pythjon=2.7

### ISSUE THREAD

**Issue by rabeehkarimi** [ricedsp/rwt#14]
Hello,
I got this error when importing rwt, I appreciate your help.
Best
Rabeeh

Traceback (most recent call last):
  File "example_wavelet.py", line 4, in <module>
    from rwt import *
  File "/home/rabeehk/anaconda2/envs/mof/lib/python2.7/site-packages/rwt.py", line 29, in <module>
    _rwt = swig_import_helper()
  File "/home/rabeehk/anaconda2/envs/mof/lib/python2.7/site-packages/rwt.py", line 28, in swig_import_helper
    return importlib.import_module('_rwt')
  File "/home/rabeehk/anaconda2/envs/mof/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (init_rwt)

**Comment by kalliste** [comment]
Did the installation complete without errors? What files do you have in /home/rabeehk/anaconda2/envs/mof/lib/python2.7/site-packages/rwt ?

**Comment by kalliste** [comment]
It looks like others were getting this same error while attempting to use Anaconda. Currently this is not supported but you might be able to get it working by following the comments at https://github.com/ricedsp/rwt/issues/7

Will close this as a duplicate.
